/**
 * SCADA-2.0
 * Centralized 3D Factory Floor Layout Configuration
 * Defines spatial coordinates, physical bounding dimensions, orientations, and safety zones
 * for exactly the 11 Phase 1 machines (M01 - M11).
 */

export const factoryLayoutConfig = {
  floor: {
    width: 100,
    depth: 70,
    wallHeight: 3.8,
    wallThickness: 0.8,
  },
  controlRoom: {
    position: { x: -33, y: 0, z: 22 },
    size: { width: 18, height: 4.2, depth: 14 },
  },
  machines: {
    "M01": {
      machineId: "M01",
      name: "CNC Fibre Laser Cutting Machine",
      shortLabel: "CNC Laser Cutting",
      position: { x: -37, y: 0, z: -25 },
      size: { width: 12.0, height: 4.8, depth: 7.5 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "cnc_laser",
      safetyZone: { width: 14.5, depth: 10.0 },
    },
    "M02": {
      machineId: "M02",
      name: "Hydraulic Press Brake",
      shortLabel: "Hydraulic Press Brake",
      position: { x: -22, y: 0, z: -23 },
      size: { width: 9.0, height: 5.8, depth: 5.0 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "press_brake",
      safetyZone: { width: 11.0, depth: 7.5 },
    },
    "M03": {
      machineId: "M03",
      name: "Spot + TIG/MIG Welding Station",
      shortLabel: "Spot + TIG/MIG Welding",
      position: { x: -7, y: 0, z: -25 },
      size: { width: 12.5, height: 4.8, depth: 5.5 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "welding_station",
      safetyZone: { width: 14.5, depth: 8.0 },
    },
    "M04": {
      machineId: "M04",
      name: "Powder Coating Booth + Curing Oven",
      shortLabel: "Powder Coating Booth",
      position: { x: 13, y: 0, z: -24 },
      size: { width: 11.0, height: 6.2, depth: 7.5 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "powder_coating",
      safetyZone: { width: 13.0, depth: 9.5 },
    },
    "M05": {
      machineId: "M05",
      name: "Solder Paste Stencil Printer",
      shortLabel: "Stencil Printer",
      position: { x: -36, y: 0, z: 2 },
      size: { width: 6.5, height: 4.2, depth: 4.8 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "stencil_printer",
      safetyZone: { width: 8.5, depth: 7.0 },
    },
    "M06": {
      machineId: "M06",
      name: "SMT Pick and Place Machine",
      shortLabel: "SMT Pick and Place",
      position: { x: -20, y: 0, z: 2 },
      size: { width: 11.0, height: 4.6, depth: 5.4 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "smt_pick_place",
      safetyZone: { width: 13.0, depth: 7.5 },
    },
    "M07": {
      machineId: "M07",
      name: "Multizone Reflow Soldering Oven",
      shortLabel: "Reflow Soldering Oven",
      position: { x: 0, y: 0, z: 2 },
      size: { width: 14.5, height: 4.8, depth: 5.2 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "reflow_oven",
      safetyZone: { width: 16.5, depth: 7.5 },
    },
    "M08": {
      machineId: "M08",
      name: "Wave Soldering Machine",
      shortLabel: "Wave Soldering Machine",
      position: { x: 18, y: 0, z: 2 },
      size: { width: 10.0, height: 4.6, depth: 5.2 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "wave_soldering",
      safetyZone: { width: 12.0, depth: 7.5 },
    },
    "M09": {
      machineId: "M09",
      name: "Testing and Burn-In Chambers",
      shortLabel: "Testing & Burn-in Chambers",
      position: { x: 36, y: 0, z: 2 },
      size: { width: 10.5, height: 5.4, depth: 5.2 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "testing_chambers",
      safetyZone: { width: 12.5, depth: 7.5 },
    },
    "M10": {
      machineId: "M10",
      name: "Rotary Screw Air Compressor + Refrigerated Air Dryer",
      shortLabel: "Air Compressor & Dryer",
      position: { x: 34, y: 0, z: 23 },
      size: { width: 8.5, height: 5.2, depth: 5.5 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "air_compressor",
      safetyZone: { width: 11.0, depth: 8.0 },
    },
    "M11": {
      machineId: "M11",
      name: "Clean Room HVAC System",
      shortLabel: "Clean Room HVAC",
      position: { x: 37, y: 0, z: -23 },
      size: { width: 8.5, height: 5.6, depth: 6.5 },
      rotation: { x: 0, y: 0, z: 0 },
      scale: 1,
      modelType: "cleanroom_hvac",
      safetyZone: { width: 10.5, depth: 8.5 },
    },
  },
};
